In [5]:
import pandas as pd
import os
import numpy as np
os.listdir()

['.ipynb_checkpoints',
 '1_Data_Wrangling_Exploration.ipynb',
 '2_Linear_regression_Admission_Predict.ipynb',
 '3_Logistic_Regression.ipynb',
 '4_Decision_Trees.ipynb',
 '5_Random_Forest.ipynb',
 '6_K_Means_Clustering.ipynb',
 '7_dbscan_clustering.ipynb',
 '9_ARM_Market_Basket_Analysis.ipynb',
 'Admission_Predict.csv',
 'Anaconda3-2020.11-Windows-x86_64.exe',
 'Assignments',
 'balance-scale_dd.txt',
 'bank-additional-full.csv',
 'bank-additional-names.txt',
 'bill_authentication.csv',
 'cars.csv',
 'Cov_Cor.PNG',
 'data.csv',
 'diabetes.csv',
 'IMDB-Movie-Data.csv',
 'Information-Value-IV-and-Weight-of-Evidence-WOE.xlsx',
 'python_intellipaat_basic_intro.ipynb',
 'python_intro1.ipynb',
 'python_practise',
 'Untitled.ipynb']

In [8]:
dd = pd.read_csv("diabetes.csv")
dd

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [10]:
dd.isna().sum() #give the count of null value in each column
#dd.dropna()     if we have any missing value(blank,NA) then we would have dropped using this code 

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [14]:
#dividing data into independent and dependent
x= dd.iloc[:,:-1]
x #independent variables

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [16]:
y = dd.iloc[:,-1]
y  #dependent data

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [17]:
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=33175abcee2c559114788a6d168eb735251d87df9cfac05fd4a009caad16a1ce
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


In [30]:
#splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test-size=0.3,random_state=0)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)


SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (<ipython-input-30-4ac3343cce85>, line 3)

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
y_train

580    1
418    0
764    0
363    1
757    1
      ..
763    0
192    1
629    0
559    0
684    0
Name: Outcome, Length: 537, dtype: int64

In [32]:
from sklearn.tree import DecisionTreeClassifier # imported DT algorithm


In [34]:
dd_dt = DecisionTreeClassifier()
dd_dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [37]:
prediction = dd_dt.predict(x_test)
prediction #here we passed independent variables for prediction, based on the independent variable 
           #our model will predict our targeted variable, here it is y_train/test

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix


In [42]:
accuracy_score(y_test,prediction) #accuracy-score calculated accuracy using conf matrix,
                                  # it summed the diagonal and divided it bu sum of all elements of matrix


0.7445887445887446

In [43]:
confusion_matrix(y_test,prediction)

array([[127,  30],
       [ 29,  45]], dtype=int64)

In [45]:
a =(127+45)/(127+29+30+45)
a

0.7445887445887446

In [47]:
#Random forest
from sklearn.ensemble import RandomForestClassifier

In [48]:
rf = RandomForestClassifier()

In [49]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [51]:
predict_rf = rf.predict(x_test)
predict_rf

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [52]:
accuracy_score(y_test,predict_rf) #we used y_test because we have made prediction using test data

0.7705627705627706

In [53]:
confusion_matrix(y_test,predict_rf)

array([[140,  17],
       [ 36,  38]], dtype=int64)