# OOps 

In [2]:
class BankAccount:
    bal1=0
    def checkbalance(self):
        print("Your balance is ",self.bal1)
    def deposit(self,amt):
        self.bal1=self.bal1+amt
    def withdraw(self,wamt):
        if(self.bal1>wamt):
            self.bal1= self.bal1-wamt
        else:
            print('You have insufficient balance')
#we can't just directly use the class, to use it we need to store it in the variable and 
#call it by using python's dot syntax

In [3]:
obj=BankAccount()

In [4]:
obj.checkbalance()

Your balance is  0


In [5]:
obj.deposit(1000)

In [6]:
obj.checkbalance()

Your balance is  1000


In [7]:
obj.withdraw(600)

In [8]:
obj.checkbalance()

Your balance is  400


In [9]:
obj.withdraw(500)

You have insufficient balance


# creating child class(MinimumBalanceAccount) inside BankAccount 

In [10]:
class MinBalAcc(BankAccount):
    minbal=5000
    def withdraw(self,wamt1):
        if(wamt1>self.minbal):
            print("Minimum balance is ",self.minbal)
            print('you cannot withdraw ',wamt1)
        

In [11]:
obj2 = MinBalAcc()

In [12]:
obj2.withdraw(6000)

Minimum balance is  5000
you cannot withdraw  6000


In [13]:
obj2.deposit(2000)

In [14]:
obj2.checkbalance()

Your balance is  2000


# NUMPY

In [15]:
import numpy as np

In [17]:
zeros_array = np.zeros((5,5)) #we can also specify dtype inside the np.zeros to specify dtype
zeros_array
#zeros_array = np.zeros((5,5),dtype=int)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
array_10_100= np.arange(10,101,5) #first attribute is start value,second is last value,third attribute is interval
#we took 101 because it excludes last value 
array_10_100

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [25]:
array_10_100= np.arange(10,100,5).reshape(3,6)
array_10_100

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [21]:
twoD_array= np.array([10,20,30,40,50,60]).reshape(2,3)
print(twoD_array)

[[10 20 30]
 [40 50 60]]


In [27]:
twoD_array= np.arange(10,61,10).reshape(2,3)
twoD_array #another way of writing same code as above 

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [31]:
a1+a2

array([5, 7, 9])

In [32]:
a1-a2

array([-3, -3, -3])

In [33]:
a1*a2

array([ 4, 10, 18])

In [34]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [37]:
b1 = np.arange(10,91,10).reshape(3,3)
b1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [39]:
b1[:,2] #this will give values present in third col but in horizontal dir
#to get values in the shape of col write index inside []

array([30, 60, 90])

In [40]:
b1[:,[2]] #extracted 3rd column, since count starts from 0 we gave 2 for third col

array([[30],
       [60],
       [90]])

In [42]:
b1[1,:] #extracted 2nd row only


array([40, 50, 60])

In [43]:
b1[0:2,0:2] #extracted cells in intersection of first 2 rows and cols
#it excludes last value

array([[10, 20],
       [40, 50]])